# Generated by Django 2.2.17 on 2021-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(2, '未知'), (1, '男'), (0, '女')], default=2, verbose_name='性别')),
                ('idcard', models.CharField(max_length=18, unique=True, verbose_name='校园卡号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
