# Generated by Django 2.2.17 on 2021-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=123456, max_length=128, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
