# Generated by Django 3.2 on 2021-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_users_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('owner', models.CharField(max_length=18, verbose_name='文件拥有者校园卡号码')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sex', models.IntegerField(choices=[(0, 'Math'), (1, 'Further Math'), (2, 'Computer Science'), (3, 'English'), (4, 'Integrated English'), (5, 'Physics'), (6, 'Biology'), (7, 'Chemistry'), (8, 'Economics'), (9, 'Business'), (10, 'Psychology'), (11, '语文'), (12, '历史'), (13, '政治'), (14, '地理'), (15, '未知')], default=15, verbose_name='学科')),
                ('description', models.CharField(max_length=128, verbose_name='文件描述')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='default.jpeg', upload_to='avatar'),
        ),
    ]
