# Generated by Django 3.2 on 2021-10-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_auto_20211025_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='sex',
            new_name='subject',
        ),
    ]
