# Generated by Django 3.2 on 2021-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0006_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='description',
            field=models.CharField(default='无描述', max_length=128, verbose_name='文件描述'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default='Alevel_helper.docx', unique=True, upload_to='file'),
        ),
    ]
