# Generated by Django 3.2 on 2021-10-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0007_auto_20211025_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(default='Alevel_helper.docx', upload_to='file'),
        ),
    ]
