# Generated by Django 3.2 on 2021-10-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0008_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='publish',
            field=models.IntegerField(choices=[(0, '私密'), (1, '公开')], default=0, verbose_name='是否公开'),
        ),
    ]
