# Generated by Django 3.2 on 2021-10-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0012_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': '班级管理', 'verbose_name_plural': '班级管理'},
        ),
    ]
