# Generated by Django 3.2 on 2021-11-01 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0013_alter_classes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_logged_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上次登陆时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='logged_in',
            field=models.IntegerField(choices=[(0, '未登陆'), (1, '登陆')], default=0, verbose_name='登陆状态'),
        ),
    ]
