# Generated by Django 3.2 on 2021-11-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0014_auto_20211101_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True, verbose_name='上次登陆时间'),
        ),
    ]
