# Generated by Django 3.2 on 2021-11-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0017_files_publish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='publish',
            field=models.IntegerField(choices=[(0, '私密'), (1, '公开'), (2, '对部分人公开')], default=0, verbose_name='是否公开'),
        ),
    ]
